Assignment_UI/Models/Food.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Assignment_UI.Models
{
    public class Food
    {
        public int FoodId { get; set; }
        [Required,DisplayName("Name")]
        public string Name { get; set; }
        [Required,DisplayName("Unit Price")]
        public decimal UnitPrice { get; set; }
        public int? View { get; set; }
        public string? mainImage { get; set; }
        public int CategoryId { get; set; }
    }
}

Assignment_UI/Controllers/CartController.cs
using Assignment_UI.Models;
using Assignment_UI.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net.Http.Headers;
using System.Runtime.CompilerServices;
using System.Text;

namespace Assignment_UI.Controllers
{
    public class CartController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7294/api");
        readonly HttpClient _client;

        public CartController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }
        public async Task<IActionResult> Index()
        {
            var token = HttpContext.Session.GetString("Token");
            if (token == null)
            {
                TempData["error"] = "Please login first";
                return RedirectToAction("Login", "Auth");
            }
            var request = new HttpRequestMessage(HttpMethod.Get, _client.BaseAddress + "/Cart/cart-details");
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
            var response = await _client.SendAsync(request);
            var cart = new List<CartDetail>();
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                cart = JsonConvert.DeserializeObject<List<CartDetail>>(data);
                HttpContext.Session.SetString("CartCount", cart.Count.ToString());
            }
            return View(cart);
        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(int id, int quantity)
        {
            var token = HttpContext.Session.GetString("Token");
            if (token == null)
            {
                TempData["error"] = "Please login first";
                return RedirectToAction("Login", "Auth");
            }
            var details = new CartDetailVM() { FoodId = id, Quantity = quantity };
            var request = new HttpRequestMessage(HttpMethod.Post, _client.BaseAddress + "/Cart/cart-details");
            request.Content = new StringContent(JsonConvert.SerializeObject(details), Encoding.UTF8, "application/json");
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
            var response = await _client.SendAsync(request);
            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = await response.Content.ReadAsStringAsync();
            } else
            {
                TempData["error"] = await response.Content.ReadAsStringAsync();
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Remove(int id)
        {
            var token = HttpContext.Session.GetString("Token");
            if (token == null)
            {
                TempData["error"] = "Please login first";
                return RedirectToAction("Login", "Auth");
            }
            var request = new HttpRequestMessage(HttpMethod.Delete, _client.BaseAddress + $"/Cart/cart-details/{id}");
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
            var response = await _client.SendAsync(request);
            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = await response.Content.ReadAsStringAsync();
            }
            else
            {
                TempData["error"] = await response.Content.ReadAsStringAsync();
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveAll()
        {
            var token = HttpContext.Session.GetString("Token");
            if (token == null)
            {
                TempData["error"] = "Please login first";
                return RedirectToAction("Login", "Auth");
            }
            var request = new HttpRequestMessage(HttpMethod.Delete, _client.BaseAddress + $"/Cart/cart-details");
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
            var response = await _client.SendAsync(request);
            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = await response.Content.ReadAsStringAsync();
            }
            else
            {
                TempData["error"] = await response.Content.ReadAsStringAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

Assignment_UI/Controllers/FoodController.cs
using Assignment_UI.Models;
using Assignment_UI.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace Assignment_UI.Controllers
{
    public class FoodController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7294/api");
        readonly HttpClient _client;
        public FoodController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }
        public IActionResult Index(int? page)
        {
            if(page > 4)
            {
                return View();
            }
            int pageNumber = (page ?? 1);
            int pageSize = 9;
            var foods = new List<Food>();
            HttpResponseMessage response = _client.GetAsync(baseAddress + $"/Food/?page={pageNumber}&pageSize={pageSize}").Result;
            if(response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                foods = JsonConvert.DeserializeObject<List<Food>>(data);
                var foodPaging = new ProductVM()
                {   
                    Foods = foods,
                    pageNumber = pageNumber,
                    pageSize = pageSize,
                    totalItem = foods.Count,
                    pageCount = (int)Math.Ceiling(36 / (double)pageSize)
                };
                return View(foodPaging);
            }
            return View();
        }
        public IActionResult FilterLoai(int id)
        {
            var foods = new List<Food>();
            var response = _client.GetAsync(baseAddress + $"/Food/categoryid={id}").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                foods = JsonConvert.DeserializeObject<List<Food>>(data);
                var foodPaging = new ProductVM()
                {
                    Foods = foods
                };
                return View(foodPaging);
            }
            return NotFound();
        }

        public IActionResult SearchName(string query)
        {
            var foods = new List<Food>();
            var response = _client.GetAsync(baseAddress + $"/Food/name={query}").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                foods = JsonConvert.DeserializeObject<List<Food>>(data);
                var foodPaging = new ProductVM()
                {
                    Foods = foods
                };
                return View(foodPaging);
            }
            return View();
        }

        public IActionResult Filter(int? value)
        {
            decimal minrange = 0;
            decimal maxrange = 0;
            if(value == 0)
            {
                return RedirectToAction("Index");
            } else if (value == 1)
            {
                minrange = 0;
                maxrange = 16000;
            } 
            else if (value == 2)
            {
                minrange = 16000;
                maxrange = 31000;
            }
            else if (value == 3)
            {
                minrange = 32000;
                maxrange = 61000;
            }
            else if (value == 4)
            {
                minrange = 61000;
                maxrange = 100000;
            }
            else if (value == 5)
            {
                minrange = 100000;
                maxrange = 900000;
            }
            var foods = new List<Food>();
            var response = _client.GetAsync(baseAddress + $"/Food/filter?minrange={minrange}&maxrange={maxrange}").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                foods = JsonConvert.DeserializeObject<List<Food>>(data);
                var foodPaging = new ProductVM()
                {
                    Foods = foods
                };
                return View(foodPaging);
            }
            return View();
        }

        public IActionResult Sort(int? page, string sort)
        {
            if(sort == "0")
            {
                return RedirectToAction("Index");
            }
            int pageNumber = (page ?? 1);
            int pageSize = 9;
            var foods = new List<Food>();
            HttpResponseMessage response = _client.GetAsync(baseAddress + $"/Food/sort={sort}?page={pageNumber}").Result;
            ViewBag.Sort = sort;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                foods = JsonConvert.DeserializeObject<List<Food>>(data);
                var foodPaging = new ProductVM()
                {
                    Foods = foods,
                    pageNumber = pageNumber,
                    pageSize = pageSize,
                    totalItem = foods.Count,
                    pageCount = (int)Math.Ceiling(36 / (double)pageSize)
                };
                return View(foodPaging);
            }
            return View();
        }

        public IActionResult Details(int? page,int id)
        {
            int pageNumber = (page ?? 4);
            int pageSize = 4;
            var food = new Food();
            var foods = new List<Food>();
            var response = _client.GetAsync(baseAddress + $"/Food/{id}").Result;
            var getAll = _client.GetAsync(baseAddress + $"/Food/?page={pageNumber}&pageSize={pageSize}").Result;
            if (!response.IsSuccessStatusCode || !getAll.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            var datafood = response.Content.ReadAsStringAsync().Result;
            food = JsonConvert.DeserializeObject<Food>(datafood);
            var listfoods = getAll.Content.ReadAsStringAsync().Result;
            foods = JsonConvert.DeserializeObject<List<Food>>(listfoods);
            var details = new DetailViews()
            {
                food = food,
                foods = foods
            };
            return View(details);
        }
    }
}

Assignment_UI/Views/Food/Details.cshtml
@model Assignment_UI.ViewModel.DetailViews;
@{
    ViewData["title"] = "Food details";
}
<div class="container">
    <div class="mb-3 row box-shadow-edit py-3 rounded-2">
    <div class="offset-1 col-4">
        <img src="@Model.food.mainImage" width="300px" height="300px"/>
    </div>
    <div class="col-6" style="position:relative; top:30px; left:100px;">
        <div class="h2 fw-bold text-warning">@Model.food.Name.ToUpper()</div>
        <div class="h5">Giá : @Model.food.UnitPrice.ToString("#,##") vnđ</div>
        <div class="h6 py-1">Lượt xem : @Model.food.View</div>
        <div class="h6 py-1">Số lượng :</div>
        <form method="post" asp-action="AddtoCart" asp-controller="Cart" asp-route-id="@Model.food.FoodId">
            <div class="btn-group w-50 py-1">
                <button type="button" class="btn btn-warning" onclick="decrease()">-</button>
                <input type="number" class="form-control rounded-0 text-center" name="quantity" id="quantity" readonly value="1" />
                <button type="button" class="btn btn-plus btn-warning" onclick="increase()">+</button>
            </div>
            <div class="d-flex justify-content-between py-3" style="width:250px;">
                <button class="btn btn-warning">Thêm giỏ hàng</button>
            </div>
        </form>
    </div>
</div>
 <hr />
    <h4 class="fw-bold my-3">Người khác cũng đặt</h4>
    <hr />
    <div class="row">
        @foreach(var item in Model.foods)
        {
            <div class="col-3">
                <div class="card mb-3 shadow">
                    <a asp-controller="Food" asp-action="Details" asp-route-id="@item.FoodId">
                        <img src="@item.mainImage" width="100%" height="100%" />
                    </a>
                    <div class="card-body fw-bolder">
                        <a asp-controller="Product" asp-action="Details" asp-route-id="1" class="text-decoration-none text-dark">
                            @item.Name
                        </a>
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-between align-items-center">
                            @item.UnitPrice
                            <a asp-controller="Food" asp-action="Details" asp-route-id="@item.FoodId" class="btn btn-sm btn-warning rounded-2 text-dark">View Details</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<script>
    function increase(){
        document.getElementById('quantity').value++;
    }
    function decrease() {
        if (document.getElementById('quantity').value > 1) {
            document.getElementById('quantity').value--;
        }
    }
</script>

Assignment_UI/Views/Food/Filter.cshtml
@model Assignment_UI.ViewModel.ProductVM
@{
    Layout = "ListFood";
}
@await Html.PartialAsync("_ShowProduct")

Assignment_UI/Views/Food/FilterLoai.cshtml
@model Assignment_UI.ViewModel.ProductVM;
@{
    Layout = "ListFood";
}
@await Html.PartialAsync("_ShowProduct")

Assignment_UI/Views/Food/Index.cshtml
@model Assignment_UI.ViewModel.ProductVM;

@{
    Layout = "ListFood";
}

@await Html.PartialAsync("_ShowProduct")
<div>
    Trang @(Model.pageNumber) / @(Model.pageCount)
</div>
<div class="d-flex justify-content-center">
    <ul class="pagination">
        <li class="page-item @(Model.pageNumber == 1 ? "disabled": "")">
            <a class="page-link" asp-controller="Food" asp-action="Index" asp-route-page="@(Model.pageNumber - 1)"> Previous </a>
        </li>
        @for (var pg = 1; pg <= Model.pageCount; pg++)
        {
            <li class="page-item @(pg == Model.pageNumber ? "active" :"")">
                <a class="page-link" asp-controller="Food" asp-action="Index" asp-route-page="@pg"> @pg </a>
            </li>
        }
        <li class="page-item @(Model.pageNumber == Model.pageCount ? "disabled": "")">
            <a class="page-link" asp-controller="Food" asp-action="Index" asp-route-page="@(Model.pageNumber + 1)"> Next </a>
        </li>
    </ul>

</div>

Assignment_UI/Views/Food/SearchName.cshtml
@model Assignment_UI.ViewModel.ProductVM;
@{
    Layout = "ListFood";
}

@await Html.PartialAsync("_ShowProduct")

Assignment_UI/Views/Food/Sort.cshtml
@model Assignment_UI.ViewModel.ProductVM
@{
    Layout = "ListFood";
}
@await Html.PartialAsync("_ShowProduct")
<div>
    Trang @(Model.pageNumber) / @(Model.pageCount)
</div>
<div class="d-flex justify-content-center">
    <ul class="pagination">
        <li class="page-item @(Model.pageNumber == 1 ? "disabled": "")">
            <a class="page-link" asp-controller="Food" asp-action="Sort" asp-route-page="@(Model.pageNumber - 1)" asp-route-sort="@ViewBag.Sort"> Previous </a>
        </li>
        @for (var pg = 1; pg <= Model.pageCount; pg++)
        {
            <li class="page-item @(pg == Model.pageNumber ? "active" :"")">
                <a class="page-link" asp-controller="Food" asp-action="Sort" asp-route-page="@pg" asp-route-sort="@ViewBag.Sort"> @pg </a>
            </li>
        }
        <li class="page-item @(Model.pageNumber == Model.pageCount ? "disabled": "")">
            <a class="page-link" asp-controller="Food" asp-action="Sort" asp-route-page="@(Model.pageNumber + 1)" asp-route-sort="@ViewBag.Sort"> Next </a>
        </li>
    </ul>

</div>