Assignment_UI/Models/Food.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Assignment_UI.Models
{
    public class Food
    {
        public int FoodId { get; set; }
        [Required,DisplayName("Name")]
        public string Name { get; set; }
        [Required,DisplayName("Unit Price")]
        public decimal UnitPrice { get; set; }
        public int? View { get; set; }
        public string? mainImage { get; set; }
        public int CategoryId { get; set; }
    }
}

Assignment_UI/Models/Order.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Assignment_UI.Models
{
    public class Order
    {
        public string FullName { get; set; } = string.Empty;
        [Required, MaxLength(250)]
        public string Address { get; set; } = string.Empty;

        [Required, RegularExpression("^(03|06|07|08|09)[0-9]{8}$", ErrorMessage = "Phone is not valid")]
        public string PhoneNumber { get; set; } = string.Empty;
        [Required]
        public string PaymentType { get; set; } = string.Empty;
        public string PaymentStatus { get; set; } = "Chưa thanh toán";
        public string? note { get; set; }
    }
}

Assignment_UI/Controllers/FGiveController.cs
using Assignment_UI.Models;
using Assignment_UI.ViewModel;
using Assignment_UI.ViewModel.Category;
using Assignment_UI.ViewModel.Food;
using Assignment_UI.ViewModel.Order;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;

namespace Assignment_UI.Controllers
{
    public class FGiveController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7294/api");
        readonly HttpClient _client;
        public FGiveController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }
        public async Task<IActionResult> Index()
        {
            var categories = await getCategories();
            ViewBag.Catecount = categories.Count;
            var foods = await GetFood();
            ViewBag.Foodcount = foods.Count;
            var orders = await GetOrders();
            ViewBag.Ordercount = orders.Count;
            ViewBag.Profit = await getProfit();
            return View();
        }

        #region Category
        public async Task<IActionResult> Categories()
        {
            var categories = await getCategories();
            return View(categories);
        }

        [HttpGet]
        public async Task<IActionResult> CreateCate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCate(CreateCategoryUploadImage categoryCreate)
        {
            if (!ModelState.IsValid)
            {
                TempData["error"] = "fail to add new category";
                return View(categoryCreate);
            }
            if (categoryCreate.ImgFile != null && categoryCreate.ImgFile.Length > 0)
            {
                categoryCreate.category.ImageUrl = await UploadImage(categoryCreate.ImgFile);
            }
            var request = new HttpRequestMessage(HttpMethod.Post, _client.BaseAddress + "/Category");
            request.Content = new StringContent(JsonConvert.SerializeObject(categoryCreate.category), Encoding.UTF8, "application/json");
            request.Headers.Authorization = new AuthenticationHeaderValue("bearer", HttpContext.Session.GetString("Token"));
            var response = await _client.SendAsync(request);
            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = "Added new category";
                return RedirectToAction("Categories");
            }else
            {
                TempData["error"] = response.Content.ReadAsStringAsync();
                return View(categoryCreate);
            }
        }

        public async Task<IActionResult> DetailCate(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + $"/Category/{id}").Result;
            Category category;
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                category = JsonConvert.DeserializeObject<Category>(data);
                return View(category);
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> UpdateCate(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + $"/Category/{id}").Result;
            Category category;
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                category = JsonConvert.DeserializeObject<Category>(data);
                var upCate = new UpdateCategory
                {
                    Category = category
                };
                return View(upCate);
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCate(UpdateCategory upCategory)
        {

            if (!ModelState.IsValid)
            {
                return View(upCategory);
            }
            if(upCategory.ImageFile != null && upCategory.ImageFile.Length > 0)
            {
                upCategory.Category.ImageUrl = await UploadImage(upCategory.ImageFile);
            }
            var request = new HttpRequestMessage(HttpMethod.Put, _client.BaseAddress + "/Category");
            request.Content = new StringContent(JsonConvert.SerializeObject(upCategory.Category),Encoding.UTF8,"application/json");
            request.Headers.Authorization = new AuthenticationHeaderValue("bearer", HttpContext.Session.GetString("Token"));
            var response = await _client.SendAsync(request);
            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = "Category Updated!";
                return RedirectToAction("Categories");
            }
            else
            {
                TempData["error"] = response.Content.ReadAsStringAsync();
            }
            return View(upCategory);
        }

        public async Task<IActionResult> DeleteCate(int id)
        {
            var request = new HttpRequestMessage(HttpMethod.Delete, _client.BaseAddress + $"/Category/{id}");
            request.Headers.Authorization = new AuthenticationHeaderValue("bearer", HttpContext.Session.GetString("Token"));
            var response = await _client.SendAsync(request);
            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = "Category Deleted";
            } else
            {
                TempData["error"] = response.Content.ReadAsStringAsync();
            }
            return RedirectToAction("Categories");
        }

        public async Task<IActionResult> SearchNameCate(string query)
        {
            var request = new HttpRequestMessage(HttpMethod.Get, _client.BaseAddress + $"/Category/search-name/{query}");
            request.Headers.Authorization = new AuthenticationHeaderValue("bearer", HttpContext.Session.GetString("Token"));
            var response = await _client.SendAsync(request);
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                List<Category> categories = JsonConvert.DeserializeObject<List<Category>>(data);
                return View(categories);
            }
            return RedirectToAction("Categories", "Fgive");
        }
        #endregion

        #region Food

        public async Task<IActionResult> Food(int? page)
        {
            var foodPagination = await GetFoodPagination(page);
            return View(foodPagination);
        }

        [HttpGet]
        public IActionResult CreateFood()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateFood(UploadCreateFood createFood)
        {
            if (!ModelState.IsValid)
            {
                return View(createFood);
            }
            if(createFood.ImageFile != null && createFood.ImageFile.Length > 0)
            {
                createFood.Food.mainImage = await UploadImage(createFood.ImageFile);
            }
            var request = new HttpRequestMessage(HttpMethod.Post, _client.BaseAddress + "/Food");
            request.Content = new StringContent(JsonConvert.SerializeObject(createFood.Food),Encoding.UTF8,"application/json");
            request.Headers.Authorization = new AuthenticationHeaderValue("bearer", HttpContext.Session.GetString("Token"));
            var response = await _client.SendAsync(request);
            if(response.IsSuccessStatusCode)
            {
                TempData["success"] = "Added new food!";
                return RedirectToAction("Food");
            }
            else
            {
                TempData["error"] = response.Content.ReadAsStringAsync();
                return View(createFood);
            }
        }

        [HttpGet]
        public async Task<IActionResult> UpdateFood(int id)
        {
            Food food = new Food();
            var request = new HttpRequestMessage(HttpMethod.Get, _client.BaseAddress + $"/Food/{id}");
            var response = await _client.SendAsync(request);
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                food = JsonConvert.DeserializeObject<Food>(data);
            }
            var updateFood = new UpdateFood() { food = food };
            return View(updateFood);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFood(UpdateFood Update)
        {
            if (!ModelState.IsValid)
            {
                return View(Update);
            }
            if(Update.ImageFile != null && Update.ImageFile.Length > 0)
            {
                Update.food.mainImage = await UploadImage(Update.ImageFile);
            }
            var request = new HttpRequestMessage(HttpMethod.Put, _client.BaseAddress + "/Food");
            request.Content = new StringContent (JsonConvert.SerializeObject(Update.food), Encoding.UTF8, "application/json");
            request.Headers.Authorization = new AuthenticationHeaderValue("bearer", HttpContext.Session.GetString("Token"));
            var response = await _client.SendAsync(request);
            if (response.IsSuccessStatusCode)
            {
                TempData["success"] = "Food Updated!";
                return RedirectToAction("Food");
            }
            TempData["error"] = "Fail to Update!";
            return View(Update);
        }

        public async Task<IActionResult> DetailFood(int id)
        {
            Food food = new Food();
            var request = new HttpRequestMessage(HttpMethod.Get, _client.BaseAddress + $"/Food/{id}");

Assignment_UI/Controllers/FoodController.cs
using Assignment_UI.Models;
using Assignment_UI.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace Assignment_UI.Controllers
{
    public class FoodController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7294/api");
        readonly HttpClient _client;
        public FoodController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }
        public IActionResult Index(int? page)
        {
            if(page > 4)
            {
                return View();
            }
            int pageNumber = (page ?? 1);
            int pageSize = 9;
            var foods = new List<Food>();
            HttpResponseMessage response = _client.GetAsync(baseAddress + $"/Food/?page={pageNumber}&pageSize={pageSize}").Result;
            if(response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                foods = JsonConvert.DeserializeObject<List<Food>>(data);
                var foodPaging = new ProductVM()
                {   
                    Foods = foods,
                    pageNumber = pageNumber,
                    pageSize = pageSize,
                    totalItem = foods.Count,
                    pageCount = (int)Math.Ceiling(36 / (double)pageSize)
                };
                return View(foodPaging);
            }
            return View();
        }
        public IActionResult FilterLoai(int id)
        {
            var foods = new List<Food>();
            var response = _client.GetAsync(baseAddress + $"/Food/categoryid={id}").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                foods = JsonConvert.DeserializeObject<List<Food>>(data);
                var foodPaging = new ProductVM()
                {
                    Foods = foods
                };
                return View(foodPaging);
            }
            return NotFound();
        }

        public IActionResult SearchName(string query)
        {
            var foods = new List<Food>();
            var response = _client.GetAsync(baseAddress + $"/Food/name={query}").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                foods = JsonConvert.DeserializeObject<List<Food>>(data);
                var foodPaging = new ProductVM()
                {
                    Foods = foods
                };
                return View(foodPaging);
            }
            return View();
        }

        public IActionResult Filter(int? value)
        {
            decimal minrange = 0;
            decimal maxrange = 0;
            if(value == 0)
            {
                return RedirectToAction("Index");
            } else if (value == 1)
            {
                minrange = 0;
                maxrange = 16000;
            } 
            else if (value == 2)
            {
                minrange = 16000;
                maxrange = 31000;
            }
            else if (value == 3)
            {
                minrange = 32000;
                maxrange = 61000;
            }
            else if (value == 4)
            {
                minrange = 61000;
                maxrange = 100000;
            }
            else if (value == 5)
            {
                minrange = 100000;
                maxrange = 900000;
            }
            var foods = new List<Food>();
            var response = _client.GetAsync(baseAddress + $"/Food/filter?minrange={minrange}&maxrange={maxrange}").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                foods = JsonConvert.DeserializeObject<List<Food>>(data);
                var foodPaging = new ProductVM()
                {
                    Foods = foods
                };
                return View(foodPaging);
            }
            return View();
        }

        public IActionResult Sort(int? page, string sort)
        {
            if(sort == "0")
            {
                return RedirectToAction("Index");
            }
            int pageNumber = (page ?? 1);
            int pageSize = 9;
            var foods = new List<Food>();
            HttpResponseMessage response = _client.GetAsync(baseAddress + $"/Food/sort={sort}?page={pageNumber}").Result;
            ViewBag.Sort = sort;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                foods = JsonConvert.DeserializeObject<List<Food>>(data);
                var foodPaging = new ProductVM()
                {
                    Foods = foods,
                    pageNumber = pageNumber,
                    pageSize = pageSize,
                    totalItem = foods.Count,
                    pageCount = (int)Math.Ceiling(36 / (double)pageSize)
                };
                return View(foodPaging);
            }
            return View();
        }

        public IActionResult Details(int? page,int id)
        {
            int pageNumber = (page ?? 4);
            int pageSize = 4;
            var food = new Food();
            var foods = new List<Food>();
            var response = _client.GetAsync(baseAddress + $"/Food/{id}").Result;
            var getAll = _client.GetAsync(baseAddress + $"/Food/?page={pageNumber}&pageSize={pageSize}").Result;
            if (!response.IsSuccessStatusCode || !getAll.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            var datafood = response.Content.ReadAsStringAsync().Result;
            food = JsonConvert.DeserializeObject<Food>(datafood);
            var listfoods = getAll.Content.ReadAsStringAsync().Result;
            foods = JsonConvert.DeserializeObject<List<Food>>(listfoods);
            var details = new DetailViews()
            {
                food = food,
                foods = foods
            };
            return View(details);
        }
    }
}

Assignment_UI/Views/FGive/Categories.cshtml
@model IEnumerable<Category>;
@{
    Layout = "_LayoutManage";
    ViewData["title"] = "Category";
}
<table class="table table-hover table-bordered text-center my-5">
    <thead class="table-warning">
        <tr>
            <th>Name</th>
            <th>Image</th>
            <th>
                <a asp-action="CreateCate" class="btn btn-sm btn-success">Add category</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model){
            <tr class="align-middle">
                <td>@item.Name</td>
                <td><img src="@item.ImageUrl" width="50px" /></td>
                <td>
                    <a asp-action="DetailCate" asp-controller="FGive" asp-route-id="@item.CategoryId" class="btn btn-sm btn-info">Details</a>
                    <a asp-action="UpdateCate" asp-controller="FGive" asp-route-id="@item.CategoryId" class="btn btn-sm btn-warning">Update</a>
                    <a asp-action="DeleteCate" asp-controller="FGive" asp-route-id="@item.CategoryId" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Assignment_UI/Views/FGive/CreateCate.cshtml
@model Assignment_UI.ViewModel.Category.CreateCategoryUploadImage;
@{
    Layout = "_LayoutManage";
    ViewData["title"] = "Create Category";
}
<div class="container my-3" style="height : 500px;">
    <div class="d-flex justify-content-center align-items-center h-100">
        <div class="card" style="width:60%;">
            <div class="card-header text-center h4">Create new category</div>
            <div class="card-body">
                <form asp-action="CreateCate" asp-controller="FGive" enctype="multipart/form-data">
                    <div class="my-2">
                        <label asp-for="ImgFile"></label>
                        <input class="form-control border-2" asp-for="@Model.ImgFile" />
                    </div>
                    <div class="my-2">
                        <label asp-for="category.Name"></label>
                        <input class="form-control border-2" asp-for="@Model.category.Name" placeholder="Input category name" />
                    </div>
                    <input class="form-control border-2" asp-for="@Model.category.ImageUrl" hidden/>
                    <div class="text-danger" asp-validation-summary="All"></div>
                    <button type="submit" class="btn btn-success">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>

Assignment_UI/Views/FGive/CreateFood.cshtml
@model Assignment_UI.ViewModel.Food.UploadCreateFood;
@{
    Layout = "_LayoutManage";
    ViewData["title"] = "Create Food";
}
<div class="container my-3" style="height : 500px;">
    <div class="d-flex justify-content-center align-items-center h-100">
        <div class="card" style="width:60%;">
            <div class="card-header text-center h4">Create new food</div>
            <div class="card-body">
                <form asp-action="CreateFood" asp-controller="FGive" enctype="multipart/form-data">
                    <div class="my-2">
                        <label asp-for="ImageFile"></label>
                        <input class="form-control border-2" asp-for="@Model.ImageFile" />
                    </div>
                    <div class="my-2">
                        <label asp-for="Food.Name"></label>
                        <input class="form-control border-2" asp-for="@Model.Food.Name" placeholder="Input food name" />
                        <span class="text-danger" asp-validation-for="@Model.Food.Name"></span>
                    </div>
                    <div class="my-2">
                        <label asp-for="Food.UnitPrice"></label>
                        <input class="form-control border-2" asp-for="@Model.Food.UnitPrice" placeholder="Input unit price of food" />
                        <span class="text-danger" asp-validation-for="@Model.Food.UnitPrice"></span>
                    </div>
                    <div class="my-2">
                        <label asp-for="@Model.Food.CategoryID" class="form-label">Category <span class="text-danger">*</span></label>
                        <select asp-for="@Model.Food.CategoryID" class="form-select">
                            <option value="2">Burger</option>
                            <option value="3">Gà Rán</option>
                            <option value="4">Thức Uống</option>
                            <option value="6">Ăn Vặt</option>
                            <option value="10">Combo</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>

Assignment_UI/Views/FGive/DetailCate.cshtml
@model Category;
@{
    Layout = "_LayoutManage";
    ViewData["title"] = "Category Detail";
}
<div class="container my-5">
    <div class="card" style="width:100%;">
        <div class="card-header text-center h4">Category Detail</div>
        <div class="card-body">
            <div class="row">
                <div class="col-5 text-center">
                    <img src="@Model.ImageUrl" width="200px" />
                </div>
                <div class="col-7">

                    <div class="mb-2">
                        <label asp-for="CategoryId"></label>
                        <input class="form-control border-2" asp-for="@Model.CategoryId" readonly />
                    </div>
                    <div class="mb-2">
                        <label asp-for="Name"></label>
                        <input class="form-control border-2" asp-for="@Model.Name" readonly />
                    </div>
                    <div class="mb-2">
                        <label asp-for="ImageUrl"></label>
                        <input class="form-control border-2" asp-for="@Model.ImageUrl" readonly />
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer d-flex justify-content-between">
            <a asp-action="Categories" class="btn btn-primary">Go Back</a>
            <a asp-action="UpdateCate" asp-route-id="@Model.CategoryId" class="btn btn-warning">Update this category</a>
        </div>
    </div>
</div>

Assignment_UI/Views/FGive/Food.cshtml
@model Assignment_UI.ViewModel.ProductVM;
@{
    Layout = "_LayoutManage";
    ViewData["title"] = "Foods";
}
<table class="table table-hover table-bordered text-center my-4">
    <thead class="table-warning">
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>View</th>
            <th>Image</th>
            <th>CategoryId</th>
            <th>
                <a asp-action="CreateFood" class="btn btn-sm btn-success">Add food</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Foods)
        {
            <tr class="align-middle">
                <td>@item.Name</td>
                <td>@item.UnitPrice.ToString("##,##")đ</td>
                <td>@item.View</td>
                <td><img src="@item.mainImage" width="50px" /></td>
                <td>@item.CategoryId</td>
                <td>
                    <a asp-action="DetailFood" asp-controller="FGive" asp-route-id="@item.FoodId" class="btn btn-sm btn-info">Details</a>
                    <a asp-action="UpdateFood" asp-controller="FGive" asp-route-id="@item.FoodId" class="btn btn-sm btn-warning">Update</a>
                    <a asp-action="DeleteFood" asp-controller="FGive" asp-route-id="@item.FoodId" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="d-flex justify-content-center">
    <ul class="pagination">
        <li class="page-item @(Model.pageNumber == 1 ? "disabled": "")">
            <a class="page-link" asp-controller="FGive" asp-action="Food" asp-route-page="@(Model.pageNumber - 1)"> Previous </a>
        </li>
        @for (var pg = 1; pg <= Model.pageCount; pg++)
        {
            <li class="page-item @(pg == Model.pageNumber ? "active" :"")">
                <a class="page-link" asp-controller="FGive" asp-action="Food" asp-route-page="@pg"> @pg </a>
            </li>
        }
        <li class="page-item @(Model.pageNumber == Model.pageCount ? "disabled": "")">
            <a class="page-link" asp-controller="FGive" asp-action="Food" asp-route-page="@(Model.pageNumber + 1)"> Next </a>
        </li>
    </ul>

</div>

Assignment_UI/Views/FGive/Index.cshtml
@{
    Layout = "_LayoutManage";
    ViewData["title"] = "Dashboard";
}
<div class="container my-5 mx-1">
    <div class="row">
        <div class="col-6">
            <a asp-action="Categories" class="text-decoration-none">
                <div class="card text-center fw-bold bg-info text-white">
                    <div class="card-header h4">CATEGORIES</div>
                    <div class="card-body h3">@ViewBag.Catecount</div>
                </div>
            </a>
        </div>
        <div class="col-6">
            <a asp-action="Food" class="text-decoration-none">
                <div class="card text-center fw-bold bg-warning text-white">
                    <div class="card-header h4">FOODS</div>
                    <div class="card-body h3">@ViewBag.Foodcount</div>
                </div>
            </a>
        </div>
        <div class="col mt-3">
            <a asp-action="Order" class="text-decoration-none">
                <div class="card text-center fw-bold bg-success text-white">
                    <div class="card-header h4">ORDERS</div>
                    <div class="card-body h3">@ViewBag.Ordercount</div>
                </div>
            </a>
        </div>
        <div class="col mt-3">
            <div class="card text-center fw-bold bg-danger text-white">
                <div class="card-header h4">PROFIT</div>
                <div class="card-body h3">@(ViewBag.Profit.ToString("##,## VNĐ"))</div>
            </div>
        </div>
    </div>
    
</div>

Assignment_UI/Views/FGive/SearchNameCate.cshtml
@model IEnumerable<Category>;
@{
    Layout = "_LayoutManage";
    ViewData["title"] = "Category";
}
<div class="d-flex justify-content-center align-items-center h-100">
    <div class="container">
        <form asp-controller="FGive" asp-action="SearchNameCate" class="my-5">
            <div class="d-flex">
                <input type="text" name="query" placeholder="Search by name" class="form-control me-3" />
                <button class="btn btn-primary" type="submit">Search</button>
                <a asp-action="Categories" asp-controller="FGive" class="btn btn-info">Reload</a>
            </div>
        </form>
        <table class="table table-hover table-bordered text-center">
            <thead class="table-warning">
                <tr>
                    <th>Name</th>
                    <th>Image</th>
                    <th>
                        <a asp-action="CreateCate" class="btn btn-sm btn-success">Add category</a>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="align-middle">
                        <td>@item.Name</td>
                        <td><img src="@item.ImageUrl" width="50px" /></td>
                        <td>
                            <a asp-action="DetailCate" asp-controller="FGive" asp-route-id="@item.CategoryId" class="btn btn-sm btn-info">Details</a>
                            <a asp-action="UpdateCate" asp-controller="FGive" asp-route-id="@item.CategoryId" class="btn btn-sm btn-warning">Update</a>
                            <a asp-action="DeleteCate" asp-controller="FGive" asp-route-id="@item.CategoryId" class="btn btn-sm btn-danger">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

Assignment_UI/Views/FGive/SearchNameFood.cshtml
@model Assignment_UI.ViewModel.ProductVM;
@{
    Layout = "_LayoutManage";
    ViewData["title"] = "Foods";
}
<div class="d-flex justify-content-center align-items-center">
    <div class="container">
        <form asp-controller="FGive" asp-action="SearchNameFood" class="my-2">
            <div class="d-flex">
                <input type="text" name="query" placeholder="Search by name" class="form-control me-3" />
                <button class="btn btn-primary" type="submit">Search</button>
                <a asp-action="Food" asp-controller="FGive" class="btn btn-info">Reload</a>
            </div>
        </form>
        <table class="table table-hover table-bordered text-center my-4">
            <thead class="table-warning">
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>View</th>
                    <th>Image</th>
                    <th>CategoryId</th>
                    <th>
                        <a asp-action="CreateFood" class="btn btn-sm btn-success">Add food</a>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Foods)
                {
                    <tr class="align-middle">
                        <td>@item.Name</td>
                        <td>@item.UnitPrice.ToString("##,##")đ</td>
                        <td>@item.View</td>
                        <td><img src="@item.mainImage" width="50px" /></td>
                        <td>@item.CategoryId</td>
                        <td>
                            <a asp-action="DetailFood" asp-controller="FGive" asp-route-id="@item.FoodId" class="btn btn-sm btn-info">Details</a>
                            <a asp-action="UpdateFood" asp-controller="FGive" asp-route-id="@item.FoodId" class="btn btn-sm btn-warning">Update</a>
                            <a asp-action="DeleteFood" asp-controller="FGive" asp-route-id="@item.FoodId" class="btn btn-sm btn-danger">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>